#!/bin/bash
app=orocrm

# Retrieve arguments
domain=$1
path=$2
admin=$3

# Save app settings
sudo yunohost app setting $app admin -v "$admin"

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Install PHP dependency
sudo apt-get update
sudo apt-get install -y php5-cli
sudo apt-get install -y git
sudo apt-get install -y nodejs
sudo ln -s /usr/bin/nodejs /usr/bin/node

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'orocrm' as database name and user
db_user=orocrm

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting $app mysqlpwd -v $db_pwd

# Create orocrm user
sudo useradd -d /var/www/$app $app

# Copy source files
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo git clone -b 1.4.1 https://github.com/orocrm/crm-application.git $final_path
(sudo cd $final_path && sudo git checkout -b prod)

# Update dependencies
( cd $final_path && sudo php -r "readfile('https://getcomposer.org/installer');" | sudo php)
(cd $final_path && sudo php $final_path/composer.phar install --prefer-dist --optimize-autoloader -n)

# Set permissions to movim directory
# todo setup better permissions
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sed -i "s@NAMETOCHANGE@$app@g" ../conf/php-fpm.conf
sed -i "s@PARAMDATABASE@$app@g" ../conf/parameters.yml
sed -i "s@PARAMUSERDATABASE@$db_user@g" ../conf/parameters.yml
sed -i "s@PARAMPASSWORDDATABASE@$db_pwd@g" ../conf/parameters.yml


sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
sudo cp ../conf/php-fpm.conf /etc/php5/fpm/pool.d/$app.conf
sudo cp -f ../conf/parameters.yml $final_path/app/config/parameters.yml


# Config php5-cli
# TODO

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app setting $app unprotected_uris -v "/"
sudo yunohost app ssowatconf

sudo sudo -u www-data php5 $final_path/app/console oro:install --force -n --application-url="$domain/$app" --user-email="webmaster@$domain" --user-firstname="admin" --user-lastname="admin" --user-password="admin"

sudo yunohost app ssowatconf